@baseUrl = https://localhost:7293

### Obtener empresa por id
GET {{baseUrl}}/api/Empresa
### Obtener 
GET {{baseUrl}}/api/Usuario/


Accept: application/json

### Crear Usuario admin
POST {{baseUrl}}/api/Usuario
Content-Type: application/json
Accept: application/json

{
 "noUsuario": 56,
    "nombre": "Johny",
    "apPaterno": "Guitar",
    "apMaterno": "lopez",
    "email": "johny@gmail.com",
    "rol": "Administrador",
  
    "contrasena": "batmanwashere"
}

####hola
POST {{baseUrl}}/api/Empresa/
Content-Type: application/json
Accept: application/json

{
  "idEmpresa": 4,
  "nombre": "OXXO",
  "descripcion": "Siempre listos siempre ahi.",
  "rowVersion": "AAAAAAAARlE="
}


### Login
POST {{baseUrl}}/api/LogIn/login
Content-Type: application/json
Accept: application/json

{
  "identificador":  "holacomoestas@gmail.com",
  "contrasena":  "batmaneljefe"
}
### Logout
POST {{baseUrl}}/api/LogIn/logout
Content-Type: application/json
Accept: application/json

### copias el set cookie desde el login 

GET {{baseUrl}}/api/test/testadminonly
Accept: application/json
Set-Cookie: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTYiLCJqdGkiOiJmZDdlNzIwYS02ZTM5LTQ1NWUtYTBmMi01Y2I0ZDI0OTc0MWIiLCJlbWFpbCI6ImhvbGFjb21vZXN0YXNAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbGVhZG8iLCJleHAiOjE3Nzg3OTQwMDcsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyOTMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MjkzIn0.nLkavwx3j1WkAQ3bp-woXUBJBMGQVYNaHqmFCChmyMU