###COMO DESDE EL PRINCIPIO AQUI TODOS TIENE LA MISMA CONTRA
### AQUI SOLO EXISTE UN ADMIN (MANAGER) YA QUE ES LA BD OFICIAL
### OJO YA LOS ADMINISTRADORES SON MANAGERSSSS EL CONCEPTO DE 
### ADMINISTRADOR YA NO EXISTE, SOLO MANAGERSSSS

### LOGIN COMO  MANAGER CON NUMERO
POST https://localhost:7293/api/LogIn/login
Content-Type: application/json

{
  "identificador": "1000001",
  "contrasena": "hash123"
}     

### LOGIN COMO MANAGER CON CORREO
POST https://localhost:7293/api/LogIn/login
Content-Type: application/json

{
  "identificador": "arahel.sapi@empresa.com",
  "contrasena": "hash123"
}

### LOGIN COMO  EMPLEADO CON NUMERO
POST https://localhost:7293/api/LogIn/login
Content-Type: application/json

{
  "identificador": "1000002",
  "contrasena": "Nuevascosas683!@$"
}   

### CAMBIAR CONTRASENA EMPLEADO
POST https://localhost:7293/api/Usuario/1000002/cambiar-contrasena
Content-Type: application/json

{
  "contrasenaActual": "Nuevascosas683!@$",
  "nuevaContrasena": "Nuevascosas683!@$",
  "confirmarNuevaContrasena": "Nuevascosas683!@$"
}

### RESTABLECER CONTRASENA EMPLEADO
POST https://localhost:7293/api/Usuario/1000002/restablecer-contrasena
Content-Type: application/json

{
  "nuevaContrasena": "Nuevascosas683!@$",
  "confirmarNuevaContrasena": "Nuevascosas683!@$"
}

### LOGIN COMO MANAGER
POST https://localhost:7293/api/LogIn/login
Content-Type: application/json

{
    "identificador": "1000001",
    "contrasena": "hash123"
}

### EMPLEADO QUE SI PERTENECE AL MANAGER
GET https://localhost:7293/api/Usuario/1000002

### EMPLEADO QUE NO PERTENECE
GET https://localhost:7293/api/Usuario/1000031