@baseUrl=https://localhost:7293

###

# OBTENER VACACIONES
GET {{baseUrl}}/api/Vacacion
Accept: application/json

###

# CREAR SOLICITUD DE VACACION
POST {{baseUrl}}/api/Vacacion
Content-Type: application/json
Accept: application/json

{
  "fechaInicio": "2026-05-10",
  "fechaFin": "2026-05-15",
  "solicitanteId": 1
}

###

# ERROR: FECHA FINAL MENOR A FECHA INICIAL
POST {{baseUrl}}/api/Vacacion
Content-Type: application/json
Accept: application/json

{
  "fechaInicio": "2026-05-15",
  "fechaFin": "2026-05-10",
  "solicitanteId": 1
}

###

# APROBAR SOLICITUD
POST {{baseUrl}}/api/Vacacion/1/evaluar
Content-Type: application/json
Accept: application/json

{
  "vacacionId": 1,
  "aprobadorId": 2,
  "estadoDecision": "Aprobada",
  "rowVersion": "AAAAAAAAB9E="
}

###

# RECHAZAR SOLICITUD
POST {{baseUrl}}/api/Vacacion/1/evaluar
Content-Type: application/json
Accept: application/json

{
  "vacacionId": 1,
  "aprobadorId": 2,
  "estadoDecision": "Rechazada",
  "rowVersion": "AAAAAAAAB9E="
}

###

# ERROR: ESTADO INVALIDO
POST {{baseUrl}}/api/Vacacion/1/evaluar
Content-Type: application/json
Accept: application/json

{
  "vacacionId": 1,
  "aprobadorId": 2,
  "estadoDecision": "EnProceso",
  "rowVersion": "AAAAAAAAB9E="
}